<a href="https://colab.research.google.com/github/ipavlopoulos/paremia/blob/main/spatial_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
%%capture
!gdown 1X2nRkVB54gHv9YwNLEP_tLZQ2oPYgyZS

In [3]:
import pandas as pd

sayings = pd.read_csv("sayings_wcoords.csv.gz")

In [4]:
%%capture
!gdown 1hWC-H6ZObb71O6xcF_BvmQ4zbji_bhYn # the BERT embedded texts

sayings_embedded = pd.read_pickle("sayings_embeddings.csv.gz")

In [5]:
# adding the BERT embedding per text into our original dataframe

sayings["bert"] = sayings_embedded.bert

In [6]:
# drop the duplicates
sayings = sayings[~sayings.text.duplicated(keep=False)]

# keeping ones whose area is not located
sayings_unk = sayings[sayings.place=="Άδηλου τόπου"]
sayings = sayings[sayings.place!="Άδηλου τόπου"]

# distinguish ones not **geo**located
sayings_no_ll = sayings[(sayings.lat.isna())|(sayings.lon.isna())]
sayings = sayings[(sayings.lat.notna())&(sayings.lon.notna())]

In [7]:
df = pd.DataFrame({
    "text": sayings.text, 
    "area": sayings.area, 
    "lat": sayings.lat, 
    "lon": sayings.lon, 
    "representation":sayings.bert
})

In [49]:
df

text    area        lat   
0            Απο Μαρθιού και Σεπτεβριού ίσα τα μερονύχτια   Κρήτη  35.308495  \
1             Απου πνιγεί και σκοτωθή, κακού θανατου πάει   Κρήτη  35.308495   
2                  Αυτός δεν ξέρει να ρετσινώνη το δοξάρι   Κρήτη  35.308495   
3       Η καλή δουλειά άργιο έχει κ' η κακή περγέλιο έχει   Κρήτη  35.308495   
4                     Κάθε μία κατσούνα σύρνει ομπρός τζη   Κρήτη  35.308495   
...                                                   ...     ...        ...   
119265                            Φεύγα λέρα 'π τόν γιακά  Ημαθία  40.517038   
119266  Φκιάντσ' κατ' δ'λειές ούτι τα σ'κκλιά δε τ'ς τρων  Ημαθία  40.517038   
119267  Χαμπ'λα – χαμπ'λά τα μάτια κι σφούγγα τα κουμμ...  Ημαθία  40.517038   
119268    Χουρίς υτία κι' αφουρμή χάρους ψυχή δεν παίρνει  Ημαθία  40.517038   
119269                       Ψώραβ' γίδα τ' νουρά σκαπάν'  Ημαθία  40.517038   

              lon                                     representation  
0       24.463342  [0.01300588995218277, -0.7646797895431519, 0.9...  
1       24.463342  [-0.037213459610939026, -0.12144553661346436, ...  
2       24.463342  [-0.36768558621406555, -0.19501501321792603, 1...  
3       24.463342  [-1.0229626893997192, -0.33663713932037354, 0....  
4       24.463342  [0.7727544903755188, -1.060009479522705, 0.310...  
...           ...                                                ...  
119265  22.180720  [-0.8613376021385193, 0.06331253051757812, -0....  
119266  22.180720  [0.5728021264076233, 0.0991407260298729, 0.764...  
119267  22.180720  [-0.3265528976917267, 0.3534873425960541, 1.10...  
119268  22.180720  [-0.3150862157344818, -0.23113000392913818, 1....  
119269  22.180720  [-0.2331009954214096, -0.14128278195858002, 0....  

[98047 rows x 5 columns]

In [35]:
area_counts = df.area.value_counts()
for area, count in area_counts.items():
    print(area, count)

Επτάνησος 7947
Αχαΐα 7167
Αμοργός 7081
Κύπρος 5687
Ήπειρος 5617
Κρήτη 4785
Θράκη 4444
Αρκαδία 4202
Λακωνία 3836
Μικρά Ασία 3757
Πόντος 3631
Νάξος 3158
Ιωάννινα 2652
Μακεδονία 2359
Κεφαλληνία 2232
Ρόδος 2096
Αιτωλία 2075
Κάρπαθος 1560
Σκύρος 1535
Θεσπρωτία 1497
Ανατολική Θράκη 1367
Εύβοια 1109
Λέσβος 1043
Μεσσηνία 981
Κοζάνη 952
Άνδρος 766
Αδριανούπολη 693
Σέρρες 672
Σάμος 640
Φιλιππούπολη 602
Κορινθία 590
Χίος 546
Ρούμελη 545
Αργολίδα 509
Νίσυρος 482
Μάνη 481
Καστελλόριζο (Μεγίστη) 466
Ιθάκη 423
Ημαθία 386
Θεσσαλία 367
Θήρα (Σαντορίνη) 347
Κάλυμνος 328
Λάρισα 318
Αθήνα 313
Καστοριά 312
Σύμη 252
Πήλιο 248
Κέρκυρα 220
Παξοί 217
Λευκάδα 211
Λήμνος 208
Μήλος 198
Σίφνος 185
Κύθνος 181
Ακαρνανία 166
Κως 164
Καρδίτσα 158
Καππαδοκία 155
Δαρδανέλλια (Ελλήσποντος) 151
Λέρος 148
Σύρος 131
Αιτωλοακαρνανία 124
Βοιωτία 120
Ίμβρος 118
Ικαρία 118
Τήνος 110
Τήλος 109
Ανάφη 109
Ηλεία 99
Ζάκυνθος 98
Παρνασσός 89
Πρέβεζα 82
Κύθηρα 81
Αττική 77
Νάουσα 77
Βόρειος Ήπειρος 76
Ανδρίτσαινα Ολυμπίου 70
Σμύρνη 66

In [54]:
area_counts_gt_100 = area_counts[area_counts >= 100]
area_counts_gt_100

area
Επτάνησος    7947
Αχαΐα        7167
Αμοργός      7081
Κύπρος       5687
Ήπειρος      5617
             ... 
Ίμβρος        118
Ικαρία        118
Τήνος         110
Τήλος         109
Ανάφη         109
Name: count, Length: 68, dtype: int64

In [55]:
df_100 = df[df['area'].isin(area_counts_gt_100.index)]
df_100

text    area        lat   
0            Απο Μαρθιού και Σεπτεβριού ίσα τα μερονύχτια   Κρήτη  35.308495  \
1             Απου πνιγεί και σκοτωθή, κακού θανατου πάει   Κρήτη  35.308495   
2                  Αυτός δεν ξέρει να ρετσινώνη το δοξάρι   Κρήτη  35.308495   
3       Η καλή δουλειά άργιο έχει κ' η κακή περγέλιο έχει   Κρήτη  35.308495   
4                     Κάθε μία κατσούνα σύρνει ομπρός τζη   Κρήτη  35.308495   
...                                                   ...     ...        ...   
119265                            Φεύγα λέρα 'π τόν γιακά  Ημαθία  40.517038   
119266  Φκιάντσ' κατ' δ'λειές ούτι τα σ'κκλιά δε τ'ς τρων  Ημαθία  40.517038   
119267  Χαμπ'λα – χαμπ'λά τα μάτια κι σφούγγα τα κουμμ...  Ημαθία  40.517038   
119268    Χουρίς υτία κι' αφουρμή χάρους ψυχή δεν παίρνει  Ημαθία  40.517038   
119269                       Ψώραβ' γίδα τ' νουρά σκαπάν'  Ημαθία  40.517038   

              lon                                     representation  
0       24.463342  [0.01300588995218277, -0.7646797895431519, 0.9...  
1       24.463342  [-0.037213459610939026, -0.12144553661346436, ...  
2       24.463342  [-0.36768558621406555, -0.19501501321792603, 1...  
3       24.463342  [-1.0229626893997192, -0.33663713932037354, 0....  
4       24.463342  [0.7727544903755188, -1.060009479522705, 0.310...  
...           ...                                                ...  
119265  22.180720  [-0.8613376021385193, 0.06331253051757812, -0....  
119266  22.180720  [0.5728021264076233, 0.0991407260298729, 0.764...  
119267  22.180720  [-0.3265528976917267, 0.3534873425960541, 1.10...  
119268  22.180720  [-0.3150862157344818, -0.23113000392913818, 1....  
119269  22.180720  [-0.2331009954214096, -0.14128278195858002, 0....  

[96357 rows x 5 columns]

In [57]:
from sklearn.model_selection import train_test_split

df_train, df_test = train_test_split(df_100, test_size=0.20, random_state=2023, shuffle=True, stratify=df_100.area)

print(df_train.shape[0], df_test.shape[0])

77085 19272


In [106]:
import geopy.distance

def degeocode(geocoded_areas, predictions, target_col="area"):
    classes = []
    # find the nearest geocoded area to the prediction in 2d 
    for p in predictions:
        dists = geocoded_areas.apply(lambda r: geopy.distance.geodesic( (r.lat, r.lon), (p[0], p[1])).km, axis=1)
        classes.append(geocoded_areas.iloc[dists.argmin()][target_col])
    return classes

def km_distance(geocodes, gold_locs, pred_ll, target_col="area"):
    dists = []
    for g, p in zip(gold_locs, pred_ll):
        gold_lat, gold_lon = geocodes[geocodes[target_col]==g][["lat", "lon"]].values[0]
        dists.append(geopy.distance.geodesic( (gold_lat, gold_lon), (p[0], p[1])).km)
    return pd.Series(dists)

# Benchmarking TFIDF vs BERT representations

### Predicting Longitude and Latitude Using BERT Embeddings

In [59]:
from sklearn.ensemble import ExtraTreesRegressor, ExtraTreesClassifier
import numpy as np

# fitting with BERT representations

train_embeddings = np.vstack(df_train['representation'].values)

bert_geo_model = ExtraTreesRegressor(n_jobs=-1)
bert_geo_model.fit(train_embeddings, df_train[["lat", "lon"]].values)

ExtraTreesRegressor(n_jobs=-1)

In [61]:
test_embeddings = np.vstack(df_test['representation'].values)
bert_geo_predictions = bert_geo_model.predict(test_embeddings)
print(bert_geo_predictions.shape)
bert_geo_predictions

(19272, 2)


array([[38.315234  , 24.14368619],
       [37.87179153, 24.05741488],
       [38.0949787 , 23.98080029],
       ...,
       [38.29457012, 23.95972373],
       [38.24641475, 23.4517718 ],
       [38.42692352, 23.91574865]])

In [62]:
from sklearn import metrics

metrics.mean_absolute_error(bert_geo_predictions, df_test[['lat', 'lon']].values, multioutput='raw_values')

array([1.30085205, 1.61153067])

### Predicting Area Using BERT Embeddings

In [63]:
bert_area_model = ExtraTreesClassifier(n_jobs=-1)
bert_area_model.fit(train_embeddings, df_train.area)

ExtraTreesClassifier(n_jobs=-1)

In [64]:
bert_area_predictions = bert_area_model.predict(test_embeddings)
bert_area_predictions

array(['Επτάνησος', 'Αχαΐα', 'Αμοργός', ..., 'Επτάνησος', 'Αμοργός',
       'Αμοργός'], dtype=object)

In [65]:
print(metrics.classification_report(bert_area_predictions, df_test.area))

                           precision    recall  f1-score   support

                   Άνδρος       0.01      0.09      0.02        22
                  Ήπειρος       0.14      0.10      0.12      1553
                   Ίμβρος       0.00      0.00      0.00         2
             Αδριανούπολη       0.03      0.14      0.05        28
                    Αθήνα       0.03      0.22      0.06         9
                  Αιτωλία       0.01      0.05      0.02        93
          Αιτωλοακαρνανία       0.00      0.00      0.00         5
                Ακαρνανία       0.00      0.00      0.00         2
                  Αμοργός       0.26      0.10      0.15      3594
                    Ανάφη       0.00      0.00      0.00         2
          Ανατολική Θράκη       0.03      0.14      0.04        49
                 Αργολίδα       0.03      0.21      0.05        14
                  Αρκαδία       0.07      0.12      0.09       488
                    Αχαΐα       0.37      0.14      0.20     

### Predicting Longitude and Latitude Using TF-IDF

In [83]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_geo_model = Pipeline([('vect', TfidfVectorizer()), ('clf', ExtraTreesRegressor(n_jobs=-1))])
tfidf_geo_model.fit(df_train.text, df_train[["lat", "lon"]].values)

Pipeline(steps=[('vect', TfidfVectorizer()),
                ('clf', ExtraTreesRegressor(n_jobs=-1))])

In [84]:
tfidf_geo_predictions = tfidf_geo_model.predict(df_test.text.values)
print(tfidf_geo_predictions.shape)
tfidf_geo_predictions

(19272, 2)


array([[35.54673696, 24.02474015],
       [35.5131379 , 24.0196923 ],
       [38.44058325, 23.82627652],
       ...,
       [37.51528616, 23.36989779],
       [38.12503569, 23.04225614],
       [37.49078676, 23.31028232]])

In [85]:
metrics.mean_absolute_error(tfidf_geo_predictions, df_test[['lat', 'lon']].values, multioutput='raw_values')

array([1.12543337, 1.485604  ])

### Predicting Area Using TF-IDF

In [86]:
tfidf_area_model = Pipeline([('vect', TfidfVectorizer()), ('clf', ExtraTreesClassifier(n_jobs=-1))])
tfidf_area_model.fit(df_train.text, df_train.area)

Pipeline(steps=[('vect', TfidfVectorizer()),
                ('clf', ExtraTreesClassifier(n_jobs=-1))])

In [92]:
tfidf_area_predictions = tfidf_area_model.predict(df_test.text)
tfidf_area_predictions

array(['Κύπρος', 'Κύπρος', 'Πόντος', ..., 'Λακωνία', 'Αχαΐα', 'Αχαΐα'],
      dtype=object)

In [93]:
print(metrics.classification_report(tfidf_area_predictions, df_test.area))

                           precision    recall  f1-score   support

                   Άνδρος       0.18      0.26      0.21       104
                  Ήπειρος       0.32      0.18      0.23      2006
                   Ίμβρος       0.00      0.00      0.00         6
             Αδριανούπολη       0.10      0.18      0.13        76
                    Αθήνα       0.06      0.13      0.09        30
                  Αιτωλία       0.36      0.36      0.36       423
          Αιτωλοακαρνανία       0.04      0.08      0.05        13
                Ακαρνανία       0.00      0.00      0.00         7
                  Αμοργός       0.53      0.31      0.39      2459
                    Ανάφη       0.00      0.00      0.00        12
          Ανατολική Θράκη       0.10      0.14      0.12       196
                 Αργολίδα       0.12      0.24      0.16        49
                  Αρκαδία       0.18      0.18      0.18       839
                    Αχαΐα       0.40      0.27      0.32     

# Tuning TFIDF

In [94]:
from sklearn.model_selection import GridSearchCV

grid_param = [
                {
                    "vect": [TfidfVectorizer()],
                    "vect__analyzer": ["word", "char"],
                    "vect__lowercase": [True, False],
                    "vect__max_df": [0.5],
                    "vect__min_df": [2],
                    "vect__ngram_range": [(1,1), (1,2), (1,3), (2,5)],
                    "clf": [ExtraTreesRegressor()],
                    "clf__n_estimators": range(10,100,10),
                    "clf__max_features": range(5, 20, 5)
                 },
              ]

# regression w/extratrees (lat/lon)
xtra = Pipeline([('vect', TfidfVectorizer), ('clf', ExtraTreesRegressor())])    
    
gsc = GridSearchCV(estimator=xtra, param_grid=grid_param, n_jobs=-1, scoring='r2', cv=5, verbose=1)

_train = df_train.sample(1000) # small-scale sandbox, remove this on the server
tuning_result = gsc.fit(_train.text.values, _train[["lat", "lon"]].values)

print("Best: %f using %s" % (tuning_result.best_score_, tuning_result.best_params_))

Fitting 5 folds for each of 432 candidates, totalling 2160 fits
Best: 0.061019 using {'clf': ExtraTreesRegressor(max_features=15, n_estimators=70), 'clf__max_features': 15, 'clf__n_estimators': 70, 'vect': TfidfVectorizer(analyzer='char', lowercase=False, max_df=0.5, min_df=2,
                ngram_range=(1, 3)), 'vect__analyzer': 'char', 'vect__lowercase': False, 'vect__max_df': 0.5, 'vect__min_df': 2, 'vect__ngram_range': (1, 3)}


In [95]:
for test_mean, std, param in zip(
        tuning_result.cv_results_['mean_test_score'],
        tuning_result.cv_results_['std_test_score'],
        tuning_result.cv_results_['params']):
    print(f"Score: {test_mean:.2f} ({std:.2f}) with: {param}")

Score: -0.19 (0.05) with: {'clf': ExtraTreesRegressor(max_features=15, n_estimators=70), 'clf__max_features': 5, 'clf__n_estimators': 10, 'vect': TfidfVectorizer(analyzer='char', lowercase=False, max_df=0.5, min_df=2,
                ngram_range=(1, 3)), 'vect__analyzer': 'word', 'vect__lowercase': True, 'vect__max_df': 0.5, 'vect__min_df': 2, 'vect__ngram_range': (1, 1)}
Score: -0.18 (0.04) with: {'clf': ExtraTreesRegressor(max_features=15, n_estimators=70), 'clf__max_features': 5, 'clf__n_estimators': 10, 'vect': TfidfVectorizer(analyzer='char', lowercase=False, max_df=0.5, min_df=2,
                ngram_range=(1, 3)), 'vect__analyzer': 'word', 'vect__lowercase': True, 'vect__max_df': 0.5, 'vect__min_df': 2, 'vect__ngram_range': (1, 2)}
Score: -0.17 (0.05) with: {'clf': ExtraTreesRegressor(max_features=15, n_estimators=70), 'clf__max_features': 5, 'clf__n_estimators': 10, 'vect': TfidfVectorizer(analyzer='char', lowercase=False, max_df=0.5, min_df=2,
                ngram_range=(1, 

In [96]:
tuning_result.best_params_

{'clf': ExtraTreesRegressor(max_features=15, n_estimators=70),
 'clf__max_features': 15,
 'clf__n_estimators': 70,
 'vect': TfidfVectorizer(analyzer='char', lowercase=False, max_df=0.5, min_df=2,
                 ngram_range=(1, 3)),
 'vect__analyzer': 'char',
 'vect__lowercase': False,
 'vect__max_df': 0.5,
 'vect__min_df': 2,
 'vect__ngram_range': (1, 3)}

In [97]:
model = Pipeline([('vect', tuning_result.best_params_["vect"]), ('clf', tuning_result.best_params_["clf"])])
model.fit(_train.text.values, _train[["lat", "lon"]].values)

Pipeline(steps=[('vect',
                 TfidfVectorizer(analyzer='char', lowercase=False, max_df=0.5,
                                 min_df=2, ngram_range=(1, 3))),
                ('clf', ExtraTreesRegressor(max_features=15, n_estimators=70))])

In [99]:
xtra_preds = model.predict(df_test.text.values)
print(f"MAE of lat predictions: {metrics.mean_absolute_error(df_test.lat.values, xtra_preds[:, 0]):.2f}")
print(f"MAE of lon predictions: {metrics.mean_absolute_error(df_test.lon.values, xtra_preds[:, 1]):.2f}")

MAE of lat predictions: 1.28
MAE of lon predictions: 1.61


In [107]:
# interpreting the results in terms of predicted distance
dist = km_distance(geocodes=_train.drop_duplicates("area"), 
                   gold_locs=_train.area.values, 
                   pred_ll=xtra_preds)
print(f"W/XtraTrees, {25}% of the predicted places fall within {dist.quantile(0.25):.2f}kms")
print(f"(NOTE: {len(set(df_test.area.unique())-set(df_test.area.unique()).intersection((_train.area.unique())))} areas out of the {len(set(df_test.area.unique()))} were not in the train)")

W/XtraTrees, 25% of the predicted places fall within 146.31kms
(NOTE: 4 areas out of the 68 were not in the train)


## TF-DF

In [108]:
import tensorflow as tf
import tensorflow_decision_forests as tfdf

In [109]:
embeddings_arr = np.vstack(df_train['representation'].values)

# convert numpy array to tensor
embeddings = tf.convert_to_tensor(embeddings_arr, dtype=tf.float32)

In [110]:
embeddings

<tf.Tensor: shape=(77085, 768), dtype=float32, numpy=
array([[ 0.14053239, -0.7308558 ,  0.8696693 , ...,  1.1983485 ,
        -0.49721497,  0.4537516 ],
       [-0.6920923 ,  0.08391377,  1.2510726 , ..., -0.20893349,
         0.05581681,  0.68383366],
       [-0.227305  , -0.717434  ,  0.37106586, ...,  0.88706005,
        -1.2724943 ,  0.7528038 ],
       ...,
       [-0.08039971,  0.00567011,  1.6290509 , ...,  0.56280446,
         0.6126828 ,  0.13060434],
       [-0.91731757, -0.6683588 ,  0.26397768, ...,  1.3118266 ,
        -0.68236375,  0.7196448 ],
       [-0.20041801, -0.87810254,  1.2139724 , ...,  0.1320326 ,
        -0.24505216, -0.07121552]], dtype=float32)>

In [111]:
train_ds = tf.data.Dataset.from_tensor_slices((embeddings, df_train['lon'].values)).batch(10000)
train_ds

<_BatchDataset element_spec=(TensorSpec(shape=(None, 768), dtype=tf.float32, name=None), TensorSpec(shape=(None,), dtype=tf.float64, name=None))>

In [112]:
test_embeddings_arr = np.vstack(df_test['representation'].values)

test_embeddings = tf.convert_to_tensor(test_embeddings_arr, dtype=tf.float32)

In [113]:
test_ds = tf.data.Dataset.from_tensor_slices((test_embeddings, df_test['lon'].values)).batch(10000)
test_ds

<_BatchDataset element_spec=(TensorSpec(shape=(None, 768), dtype=tf.float32, name=None), TensorSpec(shape=(None,), dtype=tf.float64, name=None))>

In [114]:
#model_1 = tfdf.keras.RandomForestModel(num_trees=100, name='lon', task = tfdf.keras.Task.REGRESSION, verbose=2)

model_1 = tfdf.keras.GradientBoostedTreesModel(num_trees=100, name='lon', task = tfdf.keras.Task.REGRESSION, verbose=2)

model_1.fit(train_ds)

Use 10 thread(s) for training
Use /var/folders/ys/l39bprrn1mv8cskyrqsspgvr0000gn/T/tmp27txgrib as temporary training directory
Reading training dataset...


[WARNING 23-05-23 13:42:12.0885 EEST gradient_boosted_trees.cc:1797] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 23-05-23 13:42:12.0906 EEST gradient_boosted_trees.cc:1808] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 23-05-23 13:42:12.0906 EEST gradient_boosted_trees.cc:1822] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".


Training tensor examples:
Features: Tensor("data:0", shape=(None, 768), dtype=float32)
Label: Tensor("data_1:0", shape=(None,), dtype=float64)
Weights: None
Normalized tensor features:
 {'data:0.0': SemanticTensor(semantic=<Semantic.NUMERICAL: 1>, tensor=<tf.Tensor 'strided_slice:0' shape=(None,) dtype=float32>), 'data:0.1': SemanticTensor(semantic=<Semantic.NUMERICAL: 1>, tensor=<tf.Tensor 'strided_slice_1:0' shape=(None,) dtype=float32>), 'data:0.2': SemanticTensor(semantic=<Semantic.NUMERICAL: 1>, tensor=<tf.Tensor 'strided_slice_2:0' shape=(None,) dtype=float32>), 'data:0.3': SemanticTensor(semantic=<Semantic.NUMERICAL: 1>, tensor=<tf.Tensor 'strided_slice_3:0' shape=(None,) dtype=float32>), 'data:0.4': SemanticTensor(semantic=<Semantic.NUMERICAL: 1>, tensor=<tf.Tensor 'strided_slice_4:0' shape=(None,) dtype=float32>), 'data:0.5': SemanticTensor(semantic=<Semantic.NUMERICAL: 1>, tensor=<tf.Tensor 'strided_slice_5:0' shape=(None,) dtype=float32>), 'data:0.6': SemanticTensor(semantic

2023-05-23 13:42:16.208404: W tensorflow/tsl/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz


Training dataset read in 0:00:05.062708. Found 77085 examples.
Training model...
Standard output detected as not visible to the user e.g. running in a notebook. Creating a training log redirection. If training gets stuck, try calling tfdf.keras.set_training_logs_redirection(False).


[INFO 23-05-23 13:42:17.1717 EEST kernel.cc:773] Start Yggdrasil model training
[INFO 23-05-23 13:42:17.1717 EEST kernel.cc:774] Collect training examples
[INFO 23-05-23 13:42:17.1718 EEST kernel.cc:787] Dataspec guide:
column_guides {
  column_name_pattern: "^__LABEL$"
  type: NUMERICAL
}
default_column_guide {
  categorial {
    max_vocab_count: 2000
  }
  discretized_numerical {
    maximum_num_bins: 255
  }
}
ignore_columns_without_guides: false
detect_numerical_as_discretized_numerical: false

[INFO 23-05-23 13:42:17.1742 EEST kernel.cc:393] Number of batches: 8
[INFO 23-05-23 13:42:17.1742 EEST kernel.cc:394] Number of examples: 77085
[INFO 23-05-23 13:42:17.6136 EEST kernel.cc:794] Training dataset:
Number of records: 77085
Number of columns: 769

Number of columns by type:
	NUMERICAL: 769 (100%)

Columns:

NUMERICAL: 769 (100%)
	0: "__LABEL" NUMERICAL mean:23.7603 min:13.2766 max:29.5874 sd:2.05542
	1: "data:0.0" NUMERICAL mean:-0.142956 min:-2.33358 max:2.40065 sd:0.559246
	2:

learner: "GRADIENT_BOOSTED_TREES"
features: "^data:0\\.0$"
features: "^data:0\\.1$"
features: "^data:0\\.10$"
features: "^data:0\\.100$"
features: "^data:0\\.101$"
features: "^data:0\\.102$"
features: "^data:0\\.103$"
features: "^data:0\\.104$"
features: "^data:0\\.105$"
features: "^data:0\\.106$"
features: "^data:0\\.107$"
features: "^data:0\\.108$"
features: "^data:0\\.109$"
features: "^data:0\\.11$"
features: "^data:0\\.110$"
features: "^data:0\\.111$"
features: "^data:0\\.112$"
features: "^data:0\\.113$"
features: "^data:0\\.114$"
features: "^data:0\\.115$"
features: "^data:0\\.116$"
features: "^data:0\\.117$"
features: "^data:0\\.118$"
features: "^data:0\\.119$"
features: "^data:0\\.12$"
features: "^data:0\\.120$"
features: "^data:0\\.121$"
features: "^data:0\\.122$"
features: "^data:0\\.123$"
features: "^data:0\\.124$"
features: "^data:0\\.125$"
features: "^data:0\\.126$"
features: "^data:0\\.127$"
features: "^data:0\\.128$"
features: "^data:0\\.129$"
features: "^data:0\\.13$"
fe

[INFO 23-05-23 13:42:17.6400 EEST gradient_boosted_trees.cc:453] Default loss set to SQUARED_ERROR
[INFO 23-05-23 13:42:17.6403 EEST gradient_boosted_trees.cc:1079] Training gradient boosted tree on 77085 example(s) and 768 feature(s).
[INFO 23-05-23 13:42:17.8319 EEST gradient_boosted_trees.cc:1122] 69379 examples used for training and 7706 examples used for validation
[INFO 23-05-23 13:42:20.2362 EEST gradient_boosted_trees.cc:1521] 	num-trees:1 train-loss:2.052113 train-rmse:2.052113 valid-loss:2.058561 valid-rmse:2.058561
[INFO 23-05-23 13:42:22.2112 EEST gradient_boosted_trees.cc:1523] 	num-trees:2 train-loss:2.049326 train-rmse:2.049326 valid-loss:2.057321 valid-rmse:2.057321
[INFO 23-05-23 13:42:52.4562 EEST gradient_boosted_trees.cc:1523] 	num-trees:17 train-loss:2.016318 train-rmse:2.016318 valid-loss:2.048898 valid-rmse:2.048898
[INFO 23-05-23 13:43:24.3181 EEST gradient_boosted_trees.cc:1523] 	num-trees:33 train-loss:1.989606 train-rmse:1.989606 valid-loss:2.045664 valid-rms

Model trained in 0:03:30.614402
Compiling model...
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: could not get source code
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: could not get source code
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: could not get source code
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Model compiled.


In [115]:
model_1.compile(metrics=["mae"])
evaluation = model_1.evaluate(test_ds)

evaluation

2/2 [==============================] - 1s 135ms/step - loss: 0.0000e+00 - mae: 1.6025


[0.0, 1.602547526359558]